server:
  servlet:
    application-display-name: Camthanh-oauth2-service
  http2:
    enabled: true
  servlet.context-path: /camthanh-oauth2
  port: 9999

logging:
  level:
    org.springframework:
      security:
      oauth2: debug
      jdbc:
        core:
         JdbcTemplate: DEBUG
         StatementCreatorUtils: TRACE
    org.hibernate:
      SQL: DEBUG
      type:
        descriptor.sql.BasicBinder: TRACE
      EnumType: TRACE
      
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/camthanh_oauth2?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: Admin@123
#    driver-class-name: org.hibernate.dialect.MySQL5Dialect
        
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      format_sql: true
  jdbc.template.fetch-size: -1
