server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/
    eureka-server-port: 8761

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.cloud.netflix.zuul: TRACE
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

#security:
#  oauth2:
#    client:
#      client-id: spring-security-oauth2-read-write-client
#      client-secret: $2a$04$soeOR.QFmClXeFIrhJVLWOQxfHjsJLSpWrU1iGxcMGdu.a5hvfY4W
#      authentication-scheme: header
#      access-token-uri: http://${eureka.instance.hostname}:9999/camthanh-oauth2/oauth/token
##      user-authorization-uri: http://${eureka.instance.hostname}:9999/camthanh-oauth2/oauth/authorize
##      token-name: access_token
##      scope: read, write
##      auto-approve-scopes: '.*'
#    authorization:
#      check-token-access: isAuthenticated()
#    resource:
#      token-info-uri: http://${eureka.instance.hostname}:9999/camthanh-oauth2/oauth/check_token
#      userInfoUri: http://${eureka.instance.hostname}:9999/camthanh-oauth2/user/userInfo
#      preferTokenInfo: false
        
zuul:
  ignore-security-headers: true
  ignoredHeaders:
    - authorization
  routes:
    account:
      path: /camthanh-account/** 
      serviceId: camthanh-account
      stripPrefix: false
    book:
      path: /camthanh-book/** 
      serviceId: camthanh-book
      stripPrefix: false
    
ribbon: 
  ConnectTimeout: 180000
  ReadTimeout: 120000
  eager-load:
    enabled: true
  
#zuul:  
#  routes:    
#    account:
#      path: /account/**
#      url: http://${eureka.instance.hostname}:8081/camthanh-account/account
#    resource:      
#      path: /resource/**
#      url: http://${eureka.instance.hostname}:9001/resource
#    user:
#      path: /user/**
#      url: http://${eureka.instance.hostname}:9999/camthanh-oauth2/user

spring:
#  banner.image.location: classpath:tumblr-art-gifs-circle-wave.gif
#  aop:
#    proxy-target-class: true
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#      - id: Camthanh-account-service
#        uri: lb://camthanh-account
#        predicates:
#        - Path=/camthanh-account/**
#        filters:
#        - RewritePath=/camthanh-account/(?<path>.*), /$\{path}

  datasource:
    url: jdbc:mysql://localhost:3306/camthanh_oauth2?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: Admin@123
#    driver-class-name: org.hibernate.dialect.MySQL5Dialect
        
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      format_sql: true
  jdbc.template.fetch-size: -1
#
#  security:
#    oauth2:    
#      client:
#        accessTokenUri: http://${eureka.instance.hostname}:9999/camthanh-oauth2/oauth/token
#        userAuthorizationUri: http://${eureka.instance.hostname}:9999/camthanh-oauth2/oauth/authorize
#        clientId: spring-security-oauth2-read-write-client
#        clientSecret: $2a$04$soeOR.QFmClXeFIrhJVLWOQxfHjsJLSpWrU1iGxcMGdu.a5hvfY4W
#        scope: read,write
#        auto-approve-scopes: '.*'
#      resource:
#        userInfoUri: http://${eureka.instance.hostname}:9999/camthanh-oauth2/user/userInfo
#        preferTokenInfo: false  
#    sessions: ALWAYS
  