server:
  servlet:
    application-display-name: Camthanh-account-service
#  http2:
#    enabled: true
  servlet.context-path: /camthanh-account
  port: 8081

logging:
  level:
    org.springframework:
      security:
      oauth2: debug
      jdbc:
        core:
         JdbcTemplate: DEBUG
         StatementCreatorUtils: TRACE
    org.hibernate:
      SQL: DEBUG
      type:
        descriptor.sql.BasicBinder: TRACE
      EnumType: TRACE

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/
    eureka-server-port: 8761
         
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/camthanh_oauth2?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: Admin@123
#    driver-class-name: org.hibernate.dialect.MySQL5Dialect
        
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      format_sql: true
  jdbc.template.fetch-size: -1

  security:
    oauth2:    
      client:
        accessTokenUri: http://${eureka.instance.hostname}:9999/camthanh-oauth2/oauth/token
        userAuthorizationUri: http://${eureka.instance.hostname}:9999/camthanh-oauth2/oauth/authorize
        clientId: spring-security-oauth2-read-write-client
        clientSecret: $2a$04$soeOR.QFmClXeFIrhJVLWOQxfHjsJLSpWrU1iGxcMGdu.a5hvfY4W
        scope: read,write
        auto-approve-scopes: '.*'
      resource:
        userInfoUri: http://${eureka.instance.hostname}:9999/camthanh-oauth2/user/userInfo
        preferTokenInfo: false  
    sessions: ALWAYS
    
